#!/bin/bash

read -p "Qual o nome do usuario a redefinir: " namer
 if cat /etc/passwd |grep $namer: > /dev/null
 then
 echo " "
 else
 clear
 echo "Usuario $namer não existe"
 exit
 fi
clear
echo -e "\033[1;26mO que vc deseja redefinir ?
1) Numero de logins
2) Data de expiraçao
3) Senha do usuario"
read -p "opção: " option
if [ $option -eq 1 ]; then
read -p "Qual o novo limite de logins: " liml
rm /etc/usuarios/$namer.sh
rm /etc/tempo/$namer.sh
limit $namer $liml
exit 0
fi

if [ $option -eq 2 ]; then
echo "Qual a nova data : formato DIA/MES/ANO"
read -p ": " date
dateus=$(date -d $date '+%C%y-%m-%d' |awk -F - '{print $1"-"$3"-"$2}')
chage -E $dateus $namer 2> /dev/null
echo -e "\033[1;31mUsuario: \033[1;37m$namer \033[1;31mDate: \033[1;37m$date \033[1;31m[Data redefinida]\033[0m"
exit
fi

if [ $option -eq 3 ]
then
read -p "Nova senha para usuario $namer:" senha
(echo "$senha" ; echo "$senha") | passwd $namer 2>/dev/null
echo -e "Nova senha [\033[1;31m$senha\033[1;37m] usuario [\033[1;31m$namer\033[1;37m]\033[0m"
exit
fi

echo -e "essa opçao não existe\033[0m"
